AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectCode:
    Description: project-code
    Type: String
  CEVersion:
    Description: Compute Environment Version
    Type: String
  PipelineType:
    Description: Pipeline Type 
    Type: String
    Default: test
    AllowedValues:
      - test
      - prod   

Mappings:
  AWSVPCID:
    eu-west-2:
      Subnet: 
        - subnet-24526f4d
        - subnet-0d55d941
        - subnet-5fccb225
    us-west-1:
      Subnet:
        - subnet-4a05952c
        - subnet-d968c483
  AWSSG:
    eu-west-2:
      SecurityGroup: 
        - sg-ce3aaeb2
    us-west-1:
      SecurityGroup: 
        - sg-ce753a84

Resources:
  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ComputeEnvironmentName: !Sub "${PipelineType}-ce-pointnet-${ProjectCode}-NotSpot-${CEVersion}"
      ComputeResources:
        MaxvCpus: 96
        SecurityGroupIds:
          Fn::FindInMap:
          - AWSSG
          - Ref: AWS::Region
          - SecurityGroup
        Type: EC2
        Subnets:
          Fn::FindInMap:
          - AWSVPCID
          - Ref: AWS::Region
          - Subnet
        MinvCpus: 0
        InstanceRole: ecsInstanceRole
        InstanceTypes: 
          - g3.4xlarge
        LaunchTemplate:
          LaunchTemplateName: launch-template-pointnet
          Version: $Default
        Ec2Configuration:
          - ImageType: ECS_AL2_NVIDIA
        Tags: {"name": !Sub "${PipelineType}-ce-pointnet-${ProjectCode}-NotSpot-${CEVersion}", "projec-code": !Ref ProjectCode}
      State: ENABLED