AWSTemplateFormatVersion: 2010-09-09
Description: Job Definition by Cloudformation

Parameters: 
  ProjectCode:
    Description: project-code
    Type: String
  Version:
    Description: Compute Environment Version
    Type: String
  PipelineName:
    Description: Pipeline Name
    Type: String

Resources: 
  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: !Sub "test-job-def-${ProjectCode}-pointnet-V${Version}"
      PlatformCapabilities:
        - EC2
      ContainerProperties:
        Command:
          - commit_id:latest
          - python
          - run.py
          - input=
          - Ref::S3key
          - bucket_name=
          - Ref::S3bucket
          - !Sub "pipeline=${PipelineName}"
        Memory: 40000
        Privileged: true
        JobRoleArn: arn:aws:iam::010735330309:role/test-role-for-ecs-container-pointnet
        Vcpus: 4
        Image: 010735330309.dkr.ecr.eu-west-2.amazonaws.com/pointnet-test:latest

