Resources:
  CUSTGROUP:
    Type: 'AWS::IAM::Group'
    Properties:
      GroupName: Customer2
  INPOLICU1: 
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: limit-access-to-bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 's3:ListAllMyBuckets'
            Resource: '*'
          - Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Resource: 'arn:aws:s3:::aws-s3-bucket-banny1'
          - Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:DeleteObject'
            Resource: 'arn:aws:s3:::aws-s3-bucket-banny1/*'
      Groups: 
        - !Ref CUSTGROUP        