AWSTemplateFormatVersion: 2010-09-09
Description: Create test-role-for-ecs-container-pointnet role
Resources: 
  Role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: Allows ECS tasks to call AWS services on your behalf. Providing permissions to the pointnet docker container to access only mindtrace-point-cloud s3bucket service using this role.
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      MaxSessionDuration: 3600
      RoleName: test-role-for-ecs-container-pointnet